version: "3"

env:
  RELEASE_VERSION: v0.0.2
  ORDER_SERVICE_NAME: order
  PAYMENT_SERVICE_NAME: payment


tasks:
  release-order-proto:
    cmds:
      - task: generate-proto
        vars:
          SERVICE_NAME: ${ORDER_SERVICE_NAME}
      - task: init-go-mod
        vars:
          SERVICE_NAME: ${ORDER_SERVICE_NAME}
      - task: commit-proto-update
        vars:
          SERVICE_NAME: ${ORDER_SERVICE_NAME}
          RELEASE_VERSION: ${RELEASE_VERSION}
      - task: add-tag-to-service
        vars:
          SERVICE_NAME: ${ORDER_SERVICE_NAME}
          RELEASE_VERSION: ${RELEASE_VERSION}

  release-payment-proto:
    cmds:
      - task: generate-proto
        vars:
          SERVICE_NAME: ${PAYMENT_SERVICE_NAME}
      - task: init-go-mod
        vars:
          SERVICE_NAME: ${PAYMENT_SERVICE_NAME}
      - task: commit-proto-update
        vars:
          SERVICE_NAME: ${PAYMENT_SERVICE_NAME}
          RELEASE_VERSION: ${RELEASE_VERSION}
      - task: add-tag-to-service
        vars:
          SERVICE_NAME: ${PAYMENT_SERVICE_NAME}
          RELEASE_VERSION: ${RELEASE_VERSION}

  generate-proto:
    cmds:
      - cmd: rm -rf golang/{{ .SERVICE_NAME }}
      - cmd: mkdir -p golang/{{ .SERVICE_NAME }}
      - cmd: protoc --go_out=./golang --go_opt=paths=source_relative --go-grpc_out=./golang --go-grpc_opt=paths=source_relative ./{{ .SERVICE_NAME }}/*.proto

  init-go-mod:
    cmds:
      - cmd: cd golang/{{ .SERVICE_NAME}} && go mod init github.com/salvovitale/microservices-proto/golang/{{ .SERVICE_NAME }}
      - cmd: cd golang/{{ .SERVICE_NAME}} && go mod tidy

  commit-proto-update:
    cmds:
      - cmd: git add .
      - cmd: git commit -am "Update {{.SERVICE_NAME}} proto for release {{ .RELEASE_VERSION }}"
      - cmd: git push origin main

  add-tag-to-service:
    cmds:
      - cmd: git tag -fa golang/{{ .SERVICE_NAME }}/{{ .RELEASE_VERSION }} -m "golang/{{ .SERVICE_NAME }}/{{ .RELEASE_VERSION }}"
      - cmd: git push origin {{ .TAG }}
      - cmd: git push origin refs/tags/golang/{{ .SERVICE_NAME }}/{{ .RELEASE_VERSION }}
